### ISSUE TITLE
Publicar versão 1.0 da aplicação

### ISSUE THREAD

**Issue by ThuzyFS** [ThuzyFS/Chat-Bot#29]
Requisitos funcionais:

- [X] O jogo deve ser planejado para suportar interação através de várias mídias assíncronas: texto, áudio e vídeo Escrever o modelo ideal do jogo ou aplicação #7.
- [X] O jogo deve ter suporte a mídia síncrona: áudio sobre WebRTC Estudar transporte de mídia de áudio sobre WebRTC #32.
- [X] Rodar aplicação em servidor virtual Preparar serviços de nuvem #18.
- [X] Persistir dados dos jogadores em banco de dados não relacional Usar o banco de dados não relacional para persistência dos dados do chatbot #22.
